# Site settings
title: Elite:Dangerous Refunds
email: pibbles@elitedangerousrefunds.org
description: > # this means to ignore newlines until "baseurl:"
  Customers/Backers seeking full refunds from Frontier Developments
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://elitedangerousrefunds.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
